config/routes.rb
PoWeb::Application.routes.draw do
  resources :input_files

  resources :ratings do
    get 'next_open', :on => :collection
    get 'clear_ratings', :on => :collection
  end
  root :to => 'ratings#index'

end

app/models/input_file.rb
class InputFile
  include Mongoid::Document
  include Mongoid::Timestamps

  field :body
  field :file_type

  validates_uniqueness_of :file_type
  validates_presence_of :file_type, :body
end

app/models/rating.rb
class Rating
  include Mongoid::Document
  include Mongoid::Timestamps
  field :raw_str
  field :week, :type => Fixnum
  field :output_page
  field :status
  field :iterations, :type => Fixnum
  
  before_save do |obj|
    obj.status = 'Done' if obj.status == 'Open' && obj.output_page.present? && !(obj.output_page =~ /processing error/i)
    obj.iterations ||= 10000
  end
  
  def self.current_week
    end_of_week = Date.new(2013,9,9)
    week = 0
    17.times do
      return week if Date.today < end_of_week
      week += 1
      end_of_week += 7
    end
    return nil
  end
  def self.fresh
    new(:week => current_week, :status => 'Open', :iterations => 10000)
  end
  def self.all_sorted
    all.sort_by { |x| x.created_at || Time.local(2011,1,1) }.reverse
  end
  def created_at_tz
    created_at ? created_at - 3600*4 : nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/input_files_controller.rb
class InputFilesController < ApplicationController
  def file_for_type(file_type)
    InputFile.where(:file_type => file_type).first || InputFile.new(:file_type => file_type)
  end
  def new
    file_type = params[:id] || 'Super Bowls'
    @input_file = file_for_type(file_type)
  end
  def create
    ops = params[:input_file]
    @input_file = file_for_type(ops[:file_type])
    @input_file.body = ops[:body]
    @input_file.save!
    redirect_to :ratings
  end
  def update
    create
  end
  def show
    @input_file = file_for_type(params[:id])
    render :json => @input_file
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def index
  end
  def create
    r = Rating.create!(params[:rating].merge(:status => 'Open'))
    redirect_to '/'
  end
  def update
    r = Rating.find(params[:id])
    r.update_attributes(params[:rating])
    redirect_to '/'
  end
  def next_open
    r = Rating.where(:status => 'Open').first
    render :json => r
  end
  def show
    r = Rating.find(params[:id])
    respond_to do |format|
      format.html do
        if params[:dvoa]
          render :text => "<pre>#{r.raw_str}</pre>"
        else
          render :text => r.output_page
        end
      end
      format.json do
        render :json => r
      end
    end
  end
  def destroy
    r = Rating.find(params[:id])
    r.destroy
    redirect_to '/'
  end
  def clear_ratings
    Rating.destroy_all if params[:abc] == '92'
    redirect_to '/'
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/input_files_helper.rb
module InputFilesHelper
end

app/views/input_files/new.html.haml
= form_for @input_file do |f|
  = f.hidden_field :file_type
  %h2
    = f.object.file_type

  = f.text_area :body
  %br
  = f.submit "Update"
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PoWeb</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to 'Weeks', :ratings %> | 
  <%= link_to 'Super Bowls', new_input_file_path %><br>

  <%= yield %>

</body>
</html>

app/views/ratings/index.html.haml
#main-form
  = form_for Rating.fresh do |f|
    .whole-field
      %span.label= f.label :last_completed_week
      %span.field= f.select :week, (0..17)
    
    .whole-field
      %span.label= f.label :iterations
      %span.field= f.text_field :iterations, :size => 4
    %br
    
    = f.label :ratings
    %br
    = f.text_area :raw_str, :rows => 32, :cols => 20
    %br
    = f.submit "Add Ratings"
  
%br
%br

%table
  %tr
    %th Week
    %th Status
    %th Get Page
    %th Created
    %th Delete
  - Rating.all_sorted.each do |r|
    %tr
      %td= r.week
      %td= r.status
      %td
        - if r.output_page.present?
          = link_to 'Get Page', r
      %td= r.created_at_tz ? r.created_at_tz.strftime("%m/%d %I:%M %p") : nil
      %td= link_to 'Delete', r, :method => :delete